apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ztt2yhbmb-python 
  janus-idp.io/tekton: ztt2yhbmb-python
  backstage.io/kubernetes-id: ztt2yhbmb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ztt2yhbmb-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml