apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ztt2yhbmb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ztt2yhbmb-python 
  name: ztt2yhbmb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ztt2yhbmb-python 
